install.packages("PerformanceAnalytics", repos='http://cran.rstudio.com/')
install.packages("quantstrat", repos="http://R-Forge.R-project.org")
install.packages("blotter", repos="http://R-Forge.R-project.org")
install.packages('devtools', repos='http://cran.rstudio.com/')
install.packages(c("testthat"), repos="http://cran.rstudio.com/")
library("devtools")
devtools::install_github('dmlc/xgboost', subdir='R-package')
install.packages('dplyr', repos='http://cran.rstudio.com/')
install.packages('data.table', repos='http://cran.rstudio.com/')
install.packages('caret', repos='http://cran.rstudio.com/')
install.packages('ggplot2', repos='http://cran.rstudio.com/')
install.packages('h2o', repos='http://cran.rstudio.com/')
install.packages('ProjectTemplate', repos='http://cran.rstudio.com/')
install.packages('log4r', repos='http://cran.rstudio.com/')
install.packages('Metrics', repos='http://cran.rstudio.com/')
install.packages('xts', repos='http://cran.rstudio.com/')
install.packages('foreach', repos='http://cran.rstudio.com/')
install.packages('doParallel', repos='http://cran.rstudio.com/')
